name = "tunnill"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "45.77.171.254"
UUID = "74cf7921-b13e-4fe7-9e01-efa428349ea5"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
